### ISSUE TITLE
dynamodb/attributevalue: Add AttributeValue marshaler utilities

### ISSUE THREAD

**Issue by jasdel** [aws/aws-sdk-go-v2#895]
The DynamodB attribute value marshaler utilities in the v1 SDK's `/service/dynamodb/dynamoattributevalue` package were removed in the v0.25.0 update. These utilities need to be brought back, and reintroduced to the updated SDK, and refactored for the SDK's list, map, and union representations.

#### Blocking issues
* [ ] Smithy model for DynamoDB's API needs to be updated to backfill [tagged union](https://awslabs.github.io/smithy/spec/core.html#union) to the API and similar types.
* [x] codegen: SDK use API model to render parameters as value instead of pointers types #896

#### Related issues
* [ ] Consider changing default behavior for empty maps and slices #115
* [ ]  Support more than string types for map keys. #411
* [ ] Support Text(Un)marshaler interfaces to avoid using special marshalers in simple cases #645
* [ ] Encode map[string]struct{} as StringSet, not just []string #646
* [ ] Marshal does not support json.Number to Numeric data type #929

#### Related Concerns
* [ ] How should attribute value marshaler handle DynamoDB streams vs regular Dynamodb attribute values types?

**Comment by frioux** [comment]
For future people ending up here:

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue#hdr-AttributeValue_Marshaling

```
import "github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
```
